AWSTemplateFormatVersion: 2010-09-09
Description: Create the Secrets Manager Secrets for the Blink lambda
Parameters:
  BlinkUser:
    Description: Enter your Blink Username - these details will be stored in an SSM secret
    Type: String
    MinLength: 1
    NoEcho: true
  BlinkPassword:
    Description: Enter your Blink Password - these details will be stored in an SSM secret
    Type: String
    MinLength: 1
    NoEcho: true
Resources:
  BlinkSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: Blink login secret
      Name: prod/blink/login
      SecretString: !Sub '{"blinkUser": "${BlinkUser}", "blinkPassword": "${BlinkPassword}" }'
      Tags: 
        - 
          Key: Env
          Value: Prod
Outputs:
  BlinkSecretARN:
    Description: ARN of the newly created SecretsManager Secret
    Value: !Ref BlinkSecret
    Export:
      Name: BlinkSecretARN