AWSTemplateFormatVersion: 2010-09-09
Description: Create the Secrets Manager Secrets for the Blink lambda
Parameters:
  BlinkUser:
    Description: Enter your Blink Username - these details will be stored in an SSM secret
    Type: String
    MinLength: 1
    NoEcho: true
  BlinkPassword:
    Description: Enter your Blink Password - these details will be stored in an SSM secret
    Type: String
    MinLength: 1
    NoEcho: true
  SlackUrl:
    Description: Slack Webhook url to post to
    Type: String
    MinLength: 1
    NoEcho: true

Conditions:
  HasSlackUrl: !Not [ !Equals [ !Ref SlackUrl, "" ]]
Resources:
  BlinkSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: Blink login secret
      Name: prod/blink/login
      SecretString:
        'Fn::If':
          - HasSlackUrl
          - Fn::Sub: '{"blinkUser": "${BlinkUser}", "blinkPassword": "${BlinkPassword}", "slackUrl": "${SlackUrl}" }'
          - Fn::Sub: '{"blinkUser": "${BlinkUser}", "blinkPassword": "${BlinkPassword}" }'
      Tags:
        - 
          Key: Env
          Value: Prod
Outputs:
  BlinkSecretARN:
    Description: ARN of the newly created SecretsManager Secret
    Value: !Ref BlinkSecret
    Export:
      Name: BlinkSecretARN
  BlinkSecretRegion:
    Description: Region of newly created SecretsManager Secret
    Value: !Ref "AWS::Region"
    Export:
      Name: BlinkSecretRegion